version: "3.8"
services:
  app:
    #build: .
    image: zahradkar/slon:exam-app
    restart: always
    environment:
      - DB_URL=jdbc:mysql://db:3306/exam3
      - DB_USERNAME=mlazo
      - DB_PASSWORD=password
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    #    build: .
    image: mysql:8.0
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: exam3
      MYSQL_USER: mlazo
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password